<a href="https://colab.research.google.com/github/Ishagi-Yoichi/API_advanced_todo/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

Scaling

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[-0.48527551, -0.49740645, -0.48835382, ..., -0.15070833,
         0.21766565, -0.41196577],
       [-0.40311059, -1.41170854, -0.41288978, ..., -0.47121247,
        -0.52739628, -0.0857282 ],
       [ 0.40437218, -0.01704977,  0.31345158, ..., -0.44746582,
        -0.33915345, -0.87046181],
       ...,
       [-1.6896998 ,  0.28926464, -1.6030889 , ..., -0.55167883,
         0.67166304,  3.55523739],
       [-1.21229333, -0.32336417, -1.13841088, ..., -0.24448491,
        -0.44830265,  1.76974798],
       [-0.12261658,  1.00167769, -0.15655813, ..., -0.81984959,
        -0.3707909 , -1.15040892]])

In [ ]:
y_train

497    B
312    B
263    M
525    B
206    B
      ..
146    M
68     B
151    B
176    B
243    B
Name: diagnosis, Length: 455, dtype: object

Label encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

Numpy arrays to Pytorch Tensors

In [ ]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

Defining the model

In [ ]:
class SimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    #clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

    #calculate loss
    loss = -(y_train_tensor * (torch.log(y_pred)) + (1-y_train_tensor) * (torch.log(1-y_pred)))
    return loss.mean()

Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [ ]:
#create model
model = SimpleNN(x_train_tensor)

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred = model.forward(x_train_tensor)

  #loss
  loss = model.loss_function(y_pred, y_train_tensor)


  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss:{loss.item()}')

Epoch: 1, Loss:3.698703289272643
Epoch: 2, Loss:3.5767001370594684
Epoch: 3, Loss:3.455064463812912
Epoch: 4, Loss:3.330947299061563
Epoch: 5, Loss:3.195704327946319
Epoch: 6, Loss:3.0548042225238015
Epoch: 7, Loss:2.912611640829781
Epoch: 8, Loss:2.7675843389858876
Epoch: 9, Loss:2.6217289730584863
Epoch: 10, Loss:2.473053805931553
Epoch: 11, Loss:2.322636488439518
Epoch: 12, Loss:2.1695292128302937
Epoch: 13, Loss:2.015958312335255
Epoch: 14, Loss:1.8605091082873493
Epoch: 15, Loss:1.7089211068195045
Epoch: 16, Loss:1.5615521372025956
Epoch: 17, Loss:1.4246859899393478
Epoch: 18, Loss:1.2985620710979024
Epoch: 19, Loss:1.187459340941992
Epoch: 20, Loss:1.0923018465821783
Epoch: 21, Loss:1.0133249519284313
Epoch: 22, Loss:0.9498798136026606
Epoch: 23, Loss:0.9003897569371786
Epoch: 24, Loss:0.8625683555698334
Epoch: 25, Loss:0.8338682624713327

In [ ]:
model.weights

tensor([[-0.1465],
        [-0.1648],
        [ 0.4258],
        [ 0.3409],
        [ 0.0583],
        [ 0.0766],
        [-0.2197],
        [-0.2961],
        [-0.1737],
        [ 0.3724],
        [ 0.3382],
        [ 0.3658],
        [ 0.1518],
        [-0.1478],
        [-0.1938],
        [-0.1257],
        [ 0.1357],
        [-0.0947],
        [ 0.6411],
        [-0.0475],
        [ 0.1350],
        [ 0.2135],
        [ 0.0181],
        [-0.2590],
        [ 0.4645],
        [-0.2740],
        [ 0.2943],
        [-0.4812],
        [ 0.1330],
        [ 0.3488]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1025], dtype=torch.float64, requires_grad=True)

Evaluation

In [ ]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy:{accuracy.item()*100}%')

Accuracy:53.13943028450012%